http:
  host: 'localhost'
  port: 5555

db:
  postgresql:
    host: 'db.aipibtqflemuslvpoubg.supabase.co'
    port: 5432
    username: 'postgres'
    password: 'TablesJS!906970697TEST123123$test!!$'
    database: 'postgres'

auth:
  local:
    id: 1111
    name: 'superadmin'
    password: 'qwerty'
  jwt:
    access_token:
      secret: 'secret_access_test123'
      expires: '10m'
    refresh_token:
      secret: 'secret_refresh_test123'
      expires: '1h'

