http:
  host: 'localhost'
  port: 7777

db:
  postgresql:
    host: 'db.aqwjqlpvpohnfdhalogt.supabase.co'
    port: 5432
    username: 'postgres'
    password: 'TablesJSTEST000999!!!rxjsDATAstream91238491!!$'
    database: 'postgres'

auth:
  local:
    id: 1111
    name: 'superadmin'
    password: 'qwerty'
  jwt:
    access_token:
      secret: 'secret_access_9v0asd00qwe9vsdkkaj'
      expires: '1h'
    refresh_token:
      secret: 'secret_refresh_1nkjdfnkkj123j323kdf'
      expires: '30d'
