http:
  host: 'localhost'
  port: 7777

db:
  postgresql:
    host: 'db.aqwjqlpvpohnfdhalogt.supabase.co'
    port: 5432
    username: 'postgres'
    password: 'TablesJSTEST000999!!!rxjsDATAstream91238491!!$'
    database: 'postgres'